# Generated by Django 5.0.3 on 2024-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_livraison_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='name',
            new_name='client',
        ),
        migrations.AddField(
            model_name='livraison',
            name='heure_depart',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livraison',
            name='heure_livraison',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
