# Generated by Django 5.0.3 on 2024-03-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_livraison_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
