# Generated by Django 5.0.3 on 2024-03-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_livraison_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='name',
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livraison',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
