# Generated by Django 5.0.3 on 2024-03-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_route_livraison_status_alter_livraison_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='route',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='heure_depart',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
