# Generated by Django 5.0.3 on 2024-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_livraison_route_remove_livraison_heure_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='heure_depart',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
