# Generated by Django 5.0.3 on 2024-03-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_livreur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='livraisons',
            field=models.ManyToManyField(blank=True, related_name='livraison_par', to='listings.livreur'),
        ),
    ]
