# Generated by Django 5.0.3 on 2024-03-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_remove_livraison_livreur_livreur_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='livraison',
        ),
        migrations.AddField(
            model_name='livreur',
            name='livraison',
            field=models.ManyToManyField(null=True, to='listings.livraison'),
        ),
    ]
