# Generated by Django 5.0.3 on 2024-03-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_remove_livreur_livraison_livreur_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='tacheafaire',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
