# Generated by Django 5.0.3 on 2024-03-25 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_livreur_tacheafaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='tacheafaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.client'),
        ),
    ]
