# Generated by Django 5.0.3 on 2024-03-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_tacheafaire_livreur_tacheafaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='tacheafaire',
        ),
        migrations.AddField(
            model_name='livreur',
            name='tacheafaire',
            field=models.ManyToManyField(null=True, to='listings.tacheafaire'),
        ),
    ]
