# Generated by Django 5.0.3 on 2024-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_remove_livreur_tacheafaire_livreur_tacheafaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='date',
            field=models.DateField(),
        ),
    ]
