# Generated by Django 5.0.3 on 2024-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_livraison_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='heure_depart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='heure_livraison',
            field=models.DateTimeField(),
        ),
    ]
