# Generated by Django 5.0.3 on 2024-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_alter_livraison_heure_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='details_commande',
            field=models.FileField(upload_to=''),
        ),
    ]
