# Generated by Django 5.0.3 on 2024-03-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_alter_livraison_details_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='livraison',
            field=models.ManyToManyField(null=True, related_name='livraisons', to='listings.livraison'),
        ),
    ]
