# Generated by Django 5.0.3 on 2024-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_journee_livraison_journee_recuperation_journee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='aidelivreur',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuperation',
            name='aidelivreur',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
