# Generated by Django 5.0.3 on 2024-04-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_livraison_recuperation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='status',
            new_name='infodetail',
        ),
    ]
