# Generated by Django 5.0.3 on 2024-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_rename_status_livraison_infodetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
