# Generated by Django 5.0.3 on 2024-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_rename_journe_livraison_journee'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
