# Generated by Django 5.0.3 on 2024-04-14 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_client_adress_client_city_client_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distances',
            name='to',
        ),
        migrations.AddField(
            model_name='distances',
            name='to_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='to', to='listings.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distances',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='listings.client'),
        ),
    ]
