# Generated by Django 5.0.3 on 2024-04-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_remove_distances_to_distances_to_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='adresse',
            new_name='adress',
        ),
        migrations.AddField(
            model_name='livraison',
            name='city',
            field=models.CharField(blank=True, default='Montreal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='country',
            field=models.CharField(blank=True, default='Canada', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
