# Generated by Django 5.0.3 on 2024-04-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0052_alter_livraison_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
