# Generated by Django 5.0.3 on 2024-04-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0053_livraison_lat_livraison_lng_livraison_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='contact_site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='convives',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='mode_envoi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='nom_client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='num_commande',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
