# Generated by Django 5.0.3 on 2024-04-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0055_alter_livraison_convives_alter_livraison_infodetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='num_commande',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
