# Generated by Django 5.0.3 on 2024-04-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0060_alter_livraison_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='important',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
    ]
