# Generated by Django 5.0.3 on 2024-05-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0067_alter_livraison_aidelivreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
