# Generated by Django 5.0.3 on 2024-05-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0068_livraison_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='order',
        ),
        migrations.AddField(
            model_name='livraison',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
