# Generated by Django 5.0.3 on 2024-05-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0069_remove_livraison_order_livraison_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='position',
            field=models.IntegerField(default=22),
        ),
    ]
