# Generated by Django 5.0.3 on 2024-05-09 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0072_alter_livraison_adress_alter_livraison_aidelivreur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='details_commande',
        ),
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.livreur'),
        ),
    ]
