# Generated by Django 5.0.3 on 2024-05-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0074_alter_livraison_recuperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
