# Generated by Django 5.0.3 on 2024-05-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0075_alter_livraison_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='app',
            field=models.CharField(blank=True, default=' ', max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='ligne2',
            field=models.CharField(blank=True, default=' ', max_length=700, null=True),
        ),
    ]
