# Generated by Django 5.0.3 on 2024-05-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0076_livraison_app_livraison_ligne2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
