# Generated by Django 5.0.3 on 2024-05-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0079_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('todo', 'A faire'), ('route1', '1'), ('route2', '2'), ('route3', '3'), ('route4', '4'), ('route5', '5'), ('route6', '6'), ('route7', '7'), ('route8', '8'), ('route9', '9'), ('route10', '10'), ('route11', '11'), ('route12', '12'), ('route13', '13'), ('route14', '14'), ('route15', '15'), ('route16', '16'), ('route17', '17'), ('route18', '18'), ('route19', '19'), ('route20', '20')], default='todo', max_length=20),
        ),
    ]
