# Generated by Django 5.0.3 on 2024-05-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0083_remove_livraison_route_alter_livraison_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.ForeignKey(blank=True, default=21, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.route'),
        ),
    ]
