# Generated by Django 5.0.3 on 2024-05-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0084_alter_livraison_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='vendeur',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
