# Generated by Django 5.0.3 on 2024-05-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0088_alter_livraison_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
    ]
