# Generated by Django 5.0.3 on 2024-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0090_remove_livraison_photo_livraisonphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
    ]
