# Generated by Django 5.0.3 on 2024-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0093_iteminv'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminv',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
    ]
