# Generated by Django 5.0.3 on 2024-07-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0094_iteminv_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=10000)),
                ('num_contrat', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('conseillere', models.CharField(max_length=100)),
                ('nb_convive', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('heure_livraison', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.iteminv')),
                ('livraison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.livraison')),
            ],
        ),
    ]
