# Generated by Django 5.0.3 on 2024-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0095_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='item',
        ),
        migrations.AddField(
            model_name='checklist',
            name='item',
            field=models.ManyToManyField(to='listings.iteminv'),
        ),
    ]
