# Generated by Django 5.0.3 on 2024-07-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0100_remove_checklist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='item',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.iteminv'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='listings.iteminv'),
        ),
    ]
