# Generated by Django 5.0.3 on 2024-07-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0101_remove_checklist_item_alter_inventory_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='item',
        ),
        migrations.AddField(
            model_name='iteminv',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.checklist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.product')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='products',
            field=models.ManyToManyField(through='listings.ChecklistItem', to='listings.product'),
        ),
    ]
