# Generated by Django 5.0.3 on 2024-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0109_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_cours', max_length=10),
        ),
    ]
