# Generated by Django 5.0.3 on 2024-07-30 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0111_alter_checklistitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.product'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
