# Generated by Django 5.0.3 on 2024-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0117_checklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
