# Generated by Django 5.0.3 on 2024-08-28 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0122_alter_livraison_journee'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 10, 0)),
        ),
    ]
