# Generated by Django 5.0.3 on 2024-08-28 15:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0123_route_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='journee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.journee'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
