# Generated by Django 5.0.3 on 2024-08-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0124_alter_livraison_journee_alter_route_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='journee',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.journee'),
        ),
    ]
