# Generated by Django 5.0.3 on 2024-09-12 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0125_alter_livraison_journee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheafaire',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tacheafaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
        migrations.AddField(
            model_name='tacheafaire',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='heure_livraison',
            field=models.CharField(blank=True, default='.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='infodetail',
            field=models.CharField(blank=True, default='.', max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='journee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.journee'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='retourtraiteur',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], default='non', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.ForeignKey(blank=True, default=21, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='listings.route'),
        ),
        migrations.CreateModel(
            name='LivraisonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='livraison_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_photos', to='listings.livraison')),
            ],
        ),
    ]
