# Generated by Django 5.0.3 on 2024-09-17 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0130_recupfrigo_recupfrigoitem_recuplivreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recupfrigoitem',
            name='recupfrigo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items_frigo', to='listings.recupfrigo'),
        ),
    ]
