# Generated by Django 5.0.3 on 2024-09-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0132_alter_recupfrigo_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuplivreuritem',
            name='recuplivreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_livreur', to='listings.recuplivreur'),
        ),
    ]
