# Generated by Django 5.0.3 on 2024-10-03 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0139_categorycuisine_itemcuisine_ordercuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcuisine',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
