# Generated by Django 5.0.3 on 2024-10-03 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0142_ordercuisine_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcuisine',
            name='date_added',
        ),
        migrations.AddField(
            model_name='ordercuisine',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
