# Generated by Django 5.0.3 on 2024-10-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0148_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingDock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
