# Generated by Django 5.0.3 on 2024-10-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0158_remove_checklistrecupphoto_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
