# Generated by Django 5.0.3 on 2024-11-01 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0159_livreur_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='listings/media/commandesdetail')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.checklist')),
            ],
        ),
    ]
