# Generated by Django 5.0.3 on 2024-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0168_loadingdock_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingdock',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
