# Generated by Django 5.0.3 on 2024-11-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0174_alter_checklist_conseillere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('active', 'active')], default='en_cours', max_length=20),
        ),
    ]
