# Generated by Django 5.0.3 on 2024-11-27 19:15

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0176_checklist_is_active_alter_checklist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='added_on',
            field=models.DateTimeField(default=listings.models.four_hours_ago),
        ),
    ]
