# Generated by Django 5.0.3 on 2024-12-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0177_alter_checklist_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='commentaire',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
