# Generated by Django 5.1.4 on 2025-01-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0180_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='commentairedispatch',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
