# Generated by Django 5.1.4 on 2025-01-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0183_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('pending', 'pending'), ('complete', 'complete')], default='en_cours', max_length=20),
        ),
    ]
