# Generated by Django 5.1.4 on 2025-01-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0184_alter_checklistitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitychangelog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
