# Generated by Django 5.1.4 on 2025-01-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0185_quantitychangelog_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='com',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
