# Generated by Django 5.1.4 on 2025-01-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0186_checklistitem_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='previous_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
