# Generated by Django 5.1.4 on 2025-02-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0192_alter_route_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='commentaire',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
