# Generated by Django 5.1.4 on 2025-02-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0193_alter_route_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
