# Generated by Django 5.1.4 on 2025-02-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0199_rename_uploaded_at_checklistdocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdocument',
            name='adjusted_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
