# Generated by Django 5.1.4 on 2025-02-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0202_alter_category_name_remove_livraison_livreur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='livreur',
        ),
        migrations.AddField(
            model_name='route',
            name='livreur',
            field=models.ManyToManyField(blank=True, related_name='routes', to='listings.livreur'),
        ),
    ]
