# Generated by Django 5.1.4 on 2025-02-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0203_remove_route_livreur_route_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='livreur',
        ),
        migrations.AddField(
            model_name='route',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.livreur'),
        ),
    ]
