# Generated by Django 5.1.4 on 2025-03-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0207_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistdocument',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='checklistdocument',
            name='adjusted_created_at',
        ),
        migrations.AlterField(
            model_name='checklistdocument',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='listings.checklist'),
        ),
    ]
