# Generated by Django 5.1.4 on 2025-03-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0208_rename_created_at_checklistdocument_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='heure_livraison_classement',
            field=models.CharField(blank=True, default='.', max_length=100, null=True),
        ),
    ]
