# Generated by Django 5.1.4 on 2025-03-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0209_livraison_heure_livraison_classement'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='date_signature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='nom_client_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
