# Generated by Django 5.1.4 on 2025-03-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0210_livraison_date_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='photo_recup',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
        migrations.CreateModel(
            name='PhotoRecup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/media/commandesdetail')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_photos_recup', to='listings.livraison')),
            ],
        ),
    ]
