# Generated by Django 5.1.4 on 2025-03-24 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0211_livraison_photo_recup_photorecup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photorecup',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_photos_recups', to='listings.livraison'),
        ),
    ]
