# Generated by Django 5.1.4 on 2025-03-24 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0212_alter_photorecup_livraison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('prêt à rouler', 'prêt à rouler'), ('au garage', 'au garage'), ('pick up', 'pick up'), ('ne pas utiliser', 'ne pas utiliser')], default='good', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_vehicule', to='listings.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleConditionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('prêt à rouler', 'prêt à rouler'), ('au garage', 'au garage'), ('pick up', 'pick up'), ('ne pas utiliser', 'ne pas utiliser')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionhistory', to='listings.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/media/commandesdetail')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.vehicle')),
            ],
        ),
    ]
