# Generated by Django 5.1.4 on 2025-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0214_remove_vehicle_make_alter_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
