# Generated by Django 5.1.4 on 2025-03-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0215_vehicle_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='route',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehiclephoto',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleConditionHistory',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehiclePhoto',
        ),
    ]
