# Generated by Django 5.1.4 on 2025-03-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0218_alter_vehicle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livraison',
            options={'ordering': ['status', 'position']},
        ),
    ]
