# Generated by Django 5.1.4 on 2025-04-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0222_photovehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='photovehicle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings/media/videos'),
        ),
    ]
