# Generated by Django 5.1.4 on 2025-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0225_checklist_commentairemd_alter_livraison_loading_dock'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='commodite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='debut_cocktail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='debut_repas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='depart_traiteur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='fin_evenement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='fourni_client',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='fourni_salle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='heure_arrive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='heure_convives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='occasion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='type_service',
            field=models.TextField(blank=True, null=True),
        ),
    ]
