# Generated by Django 5.1.4 on 2025-04-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0227_checklistrecupphoto_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistrecupphoto',
            old_name='commentaire',
            new_name='caption',
        ),
    ]
