# Generated by Django 5.1.4 on 2025-04-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0232_checklistmdphoto_video_checklistrecupphoto_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistmdphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
        migrations.AlterField(
            model_name='checklistrecupphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
    ]
