# Generated by Django 5.1.4 on 2025-04-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0234_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='details',
        ),
        migrations.AddField(
            model_name='submission',
            name='billing_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('assiette', 'Assiette'), ('buffet_porcelaine', 'Buffet porcelaine'), ('buffet_jetable', 'Buffet jetable'), ('coffret', 'Coffret')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='guest_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cc', 'Carte de Crédit'), ('cheque', 'Chèque'), ('interac', 'Interact')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='service_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
