# Generated by Django 5.1.4 on 2025-04-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0235_remove_submission_details_submission_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
