# Generated by Django 5.1.4 on 2025-04-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0236_alter_submission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('soumission', 'Soumission'), ('commande', 'Commande')], max_length=10),
        ),
    ]
