# Generated by Django 5.1.4 on 2025-05-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0238_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('soumission_evenement', 'Soumission_événement'), ('commande_evenement', 'Commande_événement'), ('soumission_BAL_Buffet', 'Soumission_BAL_Buffet'), ('commande_BAL_Buffet', 'Commande_BAL_Buffet')], max_length=24),
        ),
    ]
