# Generated by Django 5.1.4 on 2025-05-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0244_submission_menus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='menus',
            new_name='sub_menus',
        ),
    ]
