# Generated by Django 5.1.4 on 2025-05-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0246_alter_submission_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='delivery_modes',
        ),
        migrations.AddField(
            model_name='menu',
            name='allergie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='delivery_modes',
            field=models.ManyToManyField(blank=True, to='listings.deliverymode'),
        ),
    ]
