# Generated by Django 5.1.4 on 2025-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0249_submission_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingdock',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
