# Generated by Django 5.1.4 on 2025-06-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0256_plat_nom_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='delivery_modes',
        ),
    ]
