# Generated by Django 5.1.4 on 2025-06-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0258_menu_delivery_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='nom_english',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
