# Generated by Django 5.1.4 on 2025-06-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0263_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cc', 'Carte de Crédit'), ('cheque', 'Chèque'), ('interac', 'Interac')], max_length=20, null=True),
        ),
    ]
