# Generated by Django 5.1.4 on 2025-06-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0264_alter_submission_payment_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact',
            new_name='contact_person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse_dock',
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse_lieux',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='ascenseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='carte_dock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='dock_livraison',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='escalier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='etage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cc', 'Carte de Crédit'), ('cheque', 'Chèque'), ('interac', 'Interac')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_client', to='listings.client'),
        ),
    ]
