# Generated by Django 5.1.4 on 2025-06-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0265_rename_nom_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='event_postcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
