# Generated by Django 5.1.4 on 2025-06-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0270_alter_client_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.paymentmode'),
        ),
    ]
