# Generated by Django 5.1.4 on 2025-06-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0271_alter_client_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmode',
            name='name',
            field=models.CharField(choices=[('Carte de crédit', 'Carte de crédit'), ('Chèque', 'Chèque'), ('Transfert bancaire', 'Transfert bancaire'), ('Facturation', 'Facturation')], max_length=50),
        ),
    ]
