# Generated by Django 5.1.4 on 2025-06-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0272_alter_paymentmode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='commentaire_boissons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='commentaire_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
