# Generated by Django 5.1.4 on 2025-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0273_submission_commentaire_boissons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='type_prise_de_commande',
            field=models.CharField(blank=True, choices=[('Telephone', 'Téléphone'), ('Internet', 'Internet'), ('Courriel', 'Courriel')], max_length=10, null=True),
        ),
    ]
