# Generated by Django 5.1.4 on 2025-06-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0277_remove_client_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
    ]
