# Generated by Django 5.1.4 on 2025-06-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0278_submission_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
