# Generated by Django 5.1.4 on 2025-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0279_client_ordered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymode',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
