# Generated by Django 5.1.4 on 2025-06-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0280_alter_deliverymode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
