# Generated by Django 5.1.6 on 2025-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0293_alter_checklistitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='com',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='commentaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='previous_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
