# Generated by Django 5.1.6 on 2025-09-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0294_alter_checklistitem_com_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='avec_alcool',
            field=models.BooleanField(default=False),
        ),
    ]
