# Generated by Django 5.1.6 on 2025-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0296_submission_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AddField(
            model_name='submission',
            name='status_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Historique des statuts'),
        ),
    ]
