from django.contrib import admin
from django.urls import path, include
from listings import views
from django.conf import settings
from django.conf.urls.static import static
from listings.views import save_positions
from listings.views import *
from django.urls import path, include
from listings.views import CustomPasswordChangeView, home
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views


urlpatterns = [
    
path(
        'members/password_change/',
        CustomPasswordChangeView.as_view(),
        name='password_change',
    ),
path('password_change_done/', TemplateView.as_view(template_name="registration/password_change_done.html"), name='password_change_done'),
path('select2/', include('django_select2.urls')),
path('items/<str:category>/', view_items_by_category, name='view_items_by_category'),
path('validate_checklist/<int:checklist_item_id>/', validate_checklist_item, name='validate_checklist'),
path('adjust-quantity/', views.adjust_product_quantity, name='adjust_product_quantity'),
path('admin/', admin.site.urls, name ="admin"),
path('login/', views.custom_login, name='login'),
path('associate_livraison/<int:checklist_id>/', views.associate_livraison, name='associate_livraison'),
path('livraison/<int:ip>/', views.livraison_detail, name='livraison-detail'),
path('accounts/login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
path('update_position/', save_positions, name='save_position'),
path('create-route/', views.CreateRouteView.as_view(), name='create_route'),
path('create-routeaujour/', views.CreateRouteAujourView.as_view(), name='create_routeaujour'),
path('create-routetoday/', views.CreateRouteTodayView.as_view(), name='create_routetoday'),
path('create-routedim/', views.CreateRouteDimView.as_view(), name='create_routedim'),
path('', views.home, name='home'),
path('get_checklists_for_day/<int:day>/', views.get_checklists_for_day, name='get_checklists_for_day'),
path('members/', include('members.urls')),
path('members/', include('django.contrib.auth.urls')),
path('livraisons_list/', views.livraisons_list, name = 'livraisons-list'),
path('journees_list/', views.journees_list, name = 'journees-list'),
path('journee/<int:id>/', views.journee_detail, name='journee-detail'),
path('journeevente/<int:id>/', views.journeedetailvente, name='journeedetailvente'),
path('vehicle/delete/<int:vehicle_id>/', delete_vehicle, name='delete_vehicle'),  # Add this line
path('journee/<int:id>/livreur/<int:pk>', views.dashboard, name='dashboard'),
path('livreur_list/', views.livreur_list, name = 'livreur-list'),
path('responsables/journee/<int:id>/', views.responsables, name = 'responsables'),
path('acceuilresp', views.responsableschoixjournee, name = 'acceuilresponsables'),
path('distance', DistanceView.as_view(), name = 'my_distance_view'),
path('unauthorized/', views.unauthorized_view, name='unauthorized'),
path('mapaujour', MapAujourView.as_view(), name = 'my_mapaujour_view'),
path('mapmidiaujour', MapMidiAujourView.as_view(), name = 'my_mapmidiaujour_view'),
path('mapapremaujour', MapApremAujourView.as_view(), name = 'my_mapapremaujour_view'),
path('map', MapView.as_view(), name = 'my_map_view'),
path('mapmidi', MapMidiView.as_view(), name = 'my_mapmidi_view'),
path('create-random-task/', create_random_task, name='create_random_task'),
path('mapaprem', MapApremView.as_view(), name = 'my_mapaprem_view'),
path('maptoday', MapTodayView.as_view(), name = 'my_maptoday_view'),
path('maptodaymidi', MapMidiTodayView.as_view(), name = 'my_maptodaymidi_view'),
path('maptodayaprem', MapApremTodayView.as_view(), name = 'my_maptodayaprem_view'),
path('mapdim', MapDimView.as_view(), name = 'my_mapdim_view'),
path('mapdimmidi', MapMidiDimView.as_view(), name = 'my_mapdimmidi_view'),
path('mapdimyaprem', MapApremDimView.as_view(), name = 'my_mapdimaprem_view'),
path('tacheslist', tacheslist, name = 'tacheslist'),
path('delete_distance/<str:pk>/', views.deleteDistance, name = 'deletedistance'),
path('livreur/<int:pk>/', views.livreur_detail, name='livreur-detail'),
path('livraisonstomorrow/', views.livraisonstomorrow, name='livraisonstomorrow'),
path('livraisonstoday/', views.livraisonstoday, name='livraisonstoday'),
path('livraisonsresp/', views.livraisonsresp, name='livraisonsresp'),
path('livraisonshier/', views.livraisonshier, name='livraisonshier'),
path('geocode-all-livraisons/', GeocodeAllLivraisonsView.as_view(), name='geocode_all_livraisons'),path('geocodingtoday/<int:pk>/', GeocodingTodayView.as_view(), name='geocodingtoday'),
path('recuptoday/', views.recuptoday, name='recuptoday'),
path('api/get_checklist_items_for_date/', views.get_checklist_items_for_date, name='get_checklist_items_for_date'),
path('livraisonsventes/<int:pk>/', views.livraisonsventesdetail, name='livraisonventesdetail'),
path("livraisonsdrag/", views.Livraisonsdrag.as_view(), name='livraisonsdrag'),
path('livraison/edit/<int:livraison_id>/', livraison_edit_form, name='livraison-edit-form'),
path('livraisonsdrag/<int:pk>/', views.livraisonsdrag_detail, name='livraisonsdrag-detail'),
path('delete_photo/<int:photo_id>/', delete_photo_md, name='delete_photo'),
path('livraisonsdragtoday/<int:pk>/', views.livraisonsdrag_detailtoday, name='livraisonsdrag-detailtoday'),
path('livraisonsdragtoday/<int:pk>/edit', views.livraison_edit_formtoday, name='livraison-edit-formtoday'),
path("livraisonsdragtoday/", views.Livraisonsdragtoday.as_view(), name='livraisonsdragtoday'),
path('update_status/', views.update_status, name='update_status'),
path('submit/', submit_request, name='submit_request'),  # For submitting a new Soumission or Contrat
path('manage/', manage_submissions, name='manage_submissions'),  # For managing submissions
path('submission/<int:submission_id>/', submission_detail, name='submission_detail'),
path('update_submission/<int:submission_id>/', update_submission_status, name='update_submission_status'),  # For updating submission status
path('modify-dock/', modify_dock_view, name='modify_dock_view'),  # URL pattern for modify dock
path('save_credit_card/', save_credit_card_info, name='save_credit_card_info'),
path('commentcamarche/', views.commentcamarche, name='commentcamarche'),
path('associate-livraisons/', associate_livraisons_with_docks, name='associate_livraisons_with_docks'),
path('livraisonrespdetail/<int:ip>/', views.livraisonrespdetail, name='livraisonrespdetail'),
path('routedetail/<int:id>/', views.routedetail, name='routedetail'),
path('route/update/<int:pk>/', RouteUpdateView.as_view(), name='route_update'),
path('loading-docks/', loading_docks_view, name='loading_docks_view'),
path('taskdetail/<int:id>/', views.taskdetail, name='taskdetail'),
path('livraison/<int:livraison_id>/validate/', views.validate_livraison, name='validate_livraison'),
path('checklist/<int:checklist_id>/duplicate/', views.duplicate_checklist, name='duplicate-checklist'),
path('duplicate/<int:model_id>/', duplicate_model, name='duplicate-model'),
path('update_photo/<int:pk>/', update_photo, name='update_photo'),
path('inventory/', views.inventory, name='inventory'),
path('upload_document/<int:checklist_id>/', views.upload_document, name='upload_document'),
path('delete_document/<int:document_id>/', views.delete_document, name='delete_document'),
path('update-livraison-positions/', views.update_livraison_positions, name='update-livraison-positions'),
path('get-route-livraisons/<int:route_id>/', views.get_route_livraisons, name='get_route_livraisons'),
path('product/qr/<int:product_id>/', views.generate_qr_code, name='product_qr_code'),
path('recupslist/', views.recupslist, name='recupslist'),
path('journeerecupdetail/<int:id>/', views.journeerecupdetail, name='journeerecupdetail'),
path('recupfrigo/<int:id>/', views.recupfrigo_detail, name='recupfrigo_detail'),
path('recuplivreur/<int:id>/', views.recuplivreur_detail, name='recuplivreur_detail'),
path('product/update/<int:product_id>/', views.update_product_quantity, name='product_quantity_update'),
path('import/', views.import_items, name='import_items'),
path('creerchecklist/', views.creerchecklist, name='creerchecklist'),
path('checklist/<int:checklist_id>/add/', views.add_to_checklist, name='add_to_checklist'),
path('checklist/<int:checklist_id>/', views.checklist_detail, name='checklist-detail'),
path('iteminv/<int:item_id>/', views.product_detail, name='product_detail'),
path('subtract/<int:checklist_id>/', views.subtract_to_checklist, name='subtract_checklist'),
path('voirchecklist/', views.voir_checklist, name='voir_checklist'),
path('checklistvoir/<int:checklist_id>/', views.checklistvoir_detail, name='checklistvoir-detail'),
path('edit_task_form/<int:task_id>/', views.edit_task_form, name='edit_task_form'),
path('import-xlsx/', import_xlsx, name='import_xlsx'),
path('checklist-item/<int:pk>/delete-ajax/', ChecklistItemDeleteAjaxView.as_view(), name='checklist-item-delete-ajax'),
path('update_livraison/', views.update_livraison, name='update_livraison'),
path('update_livraison_route/', views.update_livraison_route, name='update_livraison_route'),
path('create_routes/', create_routes, name='create_routes'),
path('create_routesnext/', create_routesn, name='create_routesn'),
path('create_routesnextnext/', create_routesnn, name='create_routesnn'),
path('products/', views.product_list, name='product_list'),
path('create-shift/', views.create_shift, name='create-shift'),
path('responsablelist/', responsable_list, name='responsablelist'),
path('success/', views.success_page, name='success_page'),
path('geocode_all_livraisons/', views.geocode_all_livraisons, name='geocode_all_livraisons'),
path('faq/', faq, name='faq'),
path('checklists/associate-all/', associate_all_livraisons, name='associate_all_livraisons'),
path('create_journee/', create_journee, name='create_journee'),
path('delete_livraison/<int:livraison_id>/', delete_livraison, name='delete_livraison'),  # ✅ Add this
path('bulk_edit_livraisons/', bulk_edit_livraisons, name='bulk_edit_livraisons'),
path('update_checklist_status/<int:checklist_id>/', views.update_checklist_status, name='update_checklist_status'),
path('update_checklist_item/', views.update_checklist_item, name='update_checklist_item'),  # New URL for updating
path('livraisons_without_date/', livraisons_without_date, name='livraisons_without_date'),
path('product/<int:product_id>/change-logs/', views.view_quantity_change_logs, name='view_quantity_change_logs'),
path('checklist/<int:checklist_id>/save_breuvages_report/', views.save_breuvages_report, name='save_breuvages_report'),
path('checklist/<int:checklist_id>/breuvages/', views.get_breuvages_products, name='get_breuvages_products'),
path('checklist/<int:checklist_id>/search_productsbase/', views.search_productsbase, name='search_productsbase'),
path('checklist/<int:checklist_id>/search_productsjetable/', views.search_productsjetable, name='search_productsjetable'),
path('checklist/<int:checklist_id>/search_productsbar/', views.search_productsbar, name='search_productsbar'),
path('checklist/<int:checklist_id>/search_productsdecor/', views.search_productsdecor, name='search_productsdecor'),
path('checklist/<int:checklist_id>/search_productscafe/', views.search_productscafe, name='search_productscafe'),
path('checklist/<int:checklist_id>/search_productstable/', views.search_productstable, name='search_productstable'),
path('checklist/<int:checklist_id>/search_productsverre/', views.search_productsverre, name='search_productsverre'),
path('checklist/<int:checklist_id>/search_productsporcelaine/', views.search_productsporcelaine, name='search_productsporcelaine'),
path('checklist/<int:checklist_id>/search_productscanape/', views.search_productscanape, name='search_productscanape'),
path('checklist/<int:checklist_id>/search_productscuisson/', views.search_productscuisson, name='search_productscuisson'),
path('checklist/<int:checklist_id>/search_productsservice/', views.search_productsservice, name='search_productsservice'),
path('checklist/<int:checklist_id>/search_productsdivers/', views.search_productsdivers, name='search_productsdivers'),
path('checklist/<int:checklist_id>/search_productsalcoolfort/', views.search_productsalcoolfort, name='search_productsalcoolfort'),
path('checklist/<int:checklist_id>/search_productsbieres/', views.search_productsbieres, name='search_productsbieres'),
path('checklist/<int:checklist_id>/search_productsvins/', views.search_productsvins, name='search_productsvins'),
path('checklist/<int:checklist_id>/search_productssansalcool/', views.search_productssansalcool, name='search_productssansalcool'),
path('checklist/<int:checklist_id>/search_productscfcdn/', views.search_productscfcdn, name='search_productscfcdn'),
path('md_dashboard/', views.md_dashboard, name='md_dashboard'),
path('dashboard_stats/', views.dashboard_stats, name='dashboard_stats'),
path('conseiller-dashboard/', views.conseiller_dashboard, name='conseiller_dashboard'),
path('shifts/', views.view_shifts_by_date, name='view_shifts_by_date'),
path('create-loading-dock/', create_loading_dock, name='create_loading_dock'),
path('routesfrigo/', routesfrigo, name='routesfrigo'),
path('checklistmd/<int:pk>/', ChecklistmdDetailView, name='checklistmd_detail'),  # Adjust the URL pattern as needed
path('update-task/<int:pk>/', views.update_task, name='update_task'),
path('create-recupfrigo/', create_recupfrigo, name='create_recupfrigo'),
path('create-recuplivreur/<int:livraison_id>/', create_recuplivreur, name='create_recuplivreur'),
path('create_order_cuisine/', views.create_ordercuisine, name='create_order_cuisine'),
path('orders_cuisine/', views.order_listcuisine, name='order_list_cuisine'),
path('orders_cuisine/<int:order_id>/done/', views.mark_order_donecuisine, name='mark_order_done_cuisine'),
path('orders_cuisine/<int:order_id>/delivered/', views.mark_order_deliveredcuisine, name='mark_order_delivered_cuisine'),
path('user/orders/', views.user_order_list, name='user_order_list'),
path('order/<int:order_id>/update/', views.update_order_cuisine, name='update_order_cuisine'),
path('order/<int:order_id>/delete/', views.delete_order_cuisine, name='delete_order_cuisine'),
path('route/delete/<int:route_id>/', delete_route, name='delete_route'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



htmx_urlpatterns = [
    path('sort/', views.sort, name='sort'),
    path('edit/<int:pk>/', views.edit_item, name='edit_item'),
]

urlpatterns += htmx_urlpatterns