from django.contrib import admin
from django.urls import path, include
from listings import views
from django.conf import settings
from django.conf.urls.static import static
from listings.views import save_positions
from listings.views import *
from django.urls import path, include
urlpatterns = [
path('admin/', admin.site.urls, name ="admin"),
path('login/', views.custom_login, name='login'),
path('livraison/<int:ip>/', views.livraison_detail, name='livraison-detail'),
path('update_position/', save_positions, name='save_position'),
path('', views.home, name='home'),
path('members/', include('members.urls')),
path('members/', include('django.contrib.auth.urls')),
path('livraisons_list/', views.livraisons_list, name = 'livraisons-list'),
path('journees_list/', views.journees_list, name = 'journees-list'),
path('journee/<int:id>/', views.journee_detail, name='journee-detail'),
path('journeevente/<int:id>/', views.journeedetailvente, name='journeedetailvente'),
path('journee/<int:id>/livreur/<int:pk>', views.dashboard, name='dashboard'),
path('livreur_list/', views.livreur_list, name = 'livreur-list'),
path('responsables/journee/<int:id>/', views.responsables, name = 'responsables'),
path('acceuilresp', views.responsableschoixjournee, name = 'acceuilresponsables'),
path('distance', DistanceView.as_view(), name = 'my_distance_view'),
path('unauthorized/', views.unauthorized_view, name='unauthorized'),
path('map', MapView.as_view(), name = 'my_map_view'),
path('mapmidi', MapMidiView.as_view(), name = 'my_mapmidi_view'),
path('create-random-task/', create_random_task, name='create_random_task'),
path('mapaprem', MapApremView.as_view(), name = 'my_mapaprem_view'),
path('maptoday', MapTodayView.as_view(), name = 'my_maptoday_view'),
path('maptodaymidi', MapMidiTodayView.as_view(), name = 'my_maptodaymidi_view'),
path('maptodayaprem', MapApremTodayView.as_view(), name = 'my_maptodayaprem_view'),
path('mapdim', MapDimView.as_view(), name = 'my_mapdim_view'),
path('mapdimmidi', MapMidiDimView.as_view(), name = 'my_mapdimmidi_view'),
path('mapdimyaprem', MapApremDimView.as_view(), name = 'my_mapdimaprem_view'),
path('tacheslist', tacheslist, name = 'tacheslist'),
path('delete_distance/<str:pk>/', views.deleteDistance, name = 'deletedistance'),
path('livreur/<int:pk>/', views.livreur_detail, name='livreur-detail'),
path('livraisonstomorrow/', views.livraisonstomorrow, name='livraisonstomorrow'),
path('livraisonstoday/', views.livraisonstoday, name='livraisonstoday'),
path('livraisonsresp/', views.livraisonsresp, name='livraisonsresp'),
path('livraisonshier/', views.livraisonshier, name='livraisonshier'),
path('geocode-all-livraisons/', GeocodeAllLivraisonsView.as_view(), name='geocode_all_livraisons'),path('geocodingtoday/<int:pk>/', GeocodingTodayView.as_view(), name='geocodingtoday'),
path('recuptoday/', views.recuptoday, name='recuptoday'),
path('livraisonsventes/<int:pk>/', views.livraisonsventesdetail, name='livraisonventesdetail'),
path("livraisonsdrag/", views.Livraisonsdrag.as_view(), name='livraisonsdrag'),
path('livraison/edit/<int:livraison_id>/', livraison_edit_form, name='livraison-edit-form'),
path('livraisonsdrag/<int:pk>/', views.livraisonsdrag_detail, name='livraisonsdrag-detail'),
path('livraisonsdragtoday/<int:pk>/', views.livraisonsdrag_detailtoday, name='livraisonsdrag-detailtoday'),
path('livraisonsdragtoday/<int:pk>/edit', views.livraison_edit_formtoday, name='livraison-edit-formtoday'),
path("livraisonsdragtoday/", views.Livraisonsdragtoday.as_view(), name='livraisonsdragtoday'),
path('update_status/', views.update_status, name='update_status'),
path('commentcamarche/', views.commentcamarche, name='commentcamarche'),
path('livraisonrespdetail/<int:ip>/', views.livraisonrespdetail, name='livraisonrespdetail'),
path('routedetail/<int:id>/', views.routedetail, name='routedetail'),
path('taskdetail/<int:id>/', views.taskdetail, name='taskdetail'),
path('duplicate/<int:model_id>/', duplicate_model, name='duplicate-model'),
path('update_photo/<int:pk>/', update_photo, name='update_photo'),
path('inventory/', views.inventory, name='inventory'),
path('product/qr/<int:product_id>/', views.generate_qr_code, name='product_qr_code'),
path('recupslist/', views.recupslist, name='recupslist'),
path('journeerecupdetail/<int:id>/', views.journeerecupdetail, name='journeerecupdetail'),
path('recupfrigo/<int:id>/', views.recupfrigo_detail, name='recupfrigo_detail'),
path('recuplivreur/<int:id>/', views.recuplivreur_detail, name='recuplivreur_detail'),
path('product/update/<int:product_id>/', views.update_product_quantity, name='product_quantity_update'),
path('import/', views.import_items, name='import_items'),
path('creerchecklist/', views.creerchecklist, name='creerchecklist'),
path('checklist/<int:checklist_id>/add/', views.add_to_checklist, name='add_to_checklist'),
path('checklist/<int:checklist_id>/', views.checklist_detail, name='checklist-detail'),
path('iteminv/<int:item_id>/', views.product_detail, name='product_detail'),
path('subtract/<int:checklist_id>/', views.subtract_to_checklist, name='subtract_checklist'),
path('voirchecklist/', views.voir_checklist, name='voir_checklist'),
path('checklistvoir/<int:checklist_id>/', views.checklistvoir_detail, name='checklistvoir-detail'),
path('checklist-item/<int:pk>/delete-ajax/', ChecklistItemDeleteAjaxView.as_view(), name='checklist-item-delete-ajax'),
path('update_livraison/', views.update_livraison, name='update_livraison'),
path('create_routes/', create_routes, name='create_routes'),
path('create_routesnext/', create_routesn, name='create_routesn'),
path('create_routesnextnext/', create_routesnn, name='create_routesnn'),
path('products/', views.product_list, name='product_list'),
path('create-shift/', views.create_shift, name='create-shift'),
path('responsablelist/', responsable_list, name='responsablelist'),
path('geocode_all_livraisons/', views.geocode_all_livraisons, name='geocode_all_livraisons'),
path('faq/', faq, name='faq'),
path('checklist/<int:checklist_id>/save_breuvages_report/', views.save_breuvages_report, name='save_breuvages_report'),
path('checklist/<int:checklist_id>/breuvages/', views.get_breuvages_products, name='get_breuvages_products'),
path('checklist/<int:checklist_id>/search_productsbase/', views.search_productsbase, name='search_productsbase'),
path('checklist/<int:checklist_id>/search_productsjetable/', views.search_productsjetable, name='search_productsjetable'),
path('checklist/<int:checklist_id>/search_productsbar/', views.search_productsbar, name='search_productsbar'),
path('checklist/<int:checklist_id>/search_productsdecor/', views.search_productsdecor, name='search_productsdecor'),
path('checklist/<int:checklist_id>/search_productscafe/', views.search_productscafe, name='search_productscafe'),
path('checklist/<int:checklist_id>/search_productstable/', views.search_productstable, name='search_productstable'),
path('checklist/<int:checklist_id>/search_productsverre/', views.search_productsverre, name='search_productsverre'),
path('checklist/<int:checklist_id>/search_productsporcelaine/', views.search_productsporcelaine, name='search_productsporcelaine'),
path('checklist/<int:checklist_id>/search_productscanape/', views.search_productscanape, name='search_productscanape'),
path('checklist/<int:checklist_id>/search_productscuisson/', views.search_productscuisson, name='search_productscuisson'),
path('checklist/<int:checklist_id>/search_productsservice/', views.search_productsservice, name='search_productsservice'),
path('checklist/<int:checklist_id>/search_productsdivers/', views.search_productsdivers, name='search_productsdivers'),
path('checklist/<int:checklist_id>/search_productsbreuvage/', views.search_productsbreuvage, name='search_productsbreuvage'),
path('md_dashboard/', views.md_dashboard, name='md_dashboard'),
path('shifts/', views.view_shifts_by_date, name='view_shifts_by_date'),
path('create-loading-dock/', create_loading_dock, name='create_loading_dock'),
path('routesfrigo/', routesfrigo, name='routesfrigo'),
path('checklistmd/<int:pk>/', ChecklistmdDetailView, name='checklistmd_detail'),  # Adjust the URL pattern as needed
path('update-task/<int:pk>/', views.update_task, name='update_task'),
path('create-recupfrigo/', create_recupfrigo, name='create_recupfrigo'),
path('create-recuplivreur/<int:livraison_id>/', create_recuplivreur, name='create_recuplivreur'),
path('create_order_cuisine/', views.create_ordercuisine, name='create_order_cuisine'),
path('orders_cuisine/', views.order_listcuisine, name='order_list_cuisine'),
path('orders_cuisine/<int:order_id>/done/', views.mark_order_donecuisine, name='mark_order_done_cuisine'),
path('orders_cuisine/<int:order_id>/delivered/', views.mark_order_deliveredcuisine, name='mark_order_delivered_cuisine'),
path('user/orders/', views.user_order_list, name='user_order_list'),
path('order/<int:order_id>/update/', views.update_order_cuisine, name='update_order_cuisine'),
path('order/<int:order_id>/delete/', views.delete_order_cuisine, name='delete_order_cuisine'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



htmx_urlpatterns = [
    path('delete-livraison/<int:pk>/', views.delete_livraison, name='delete-livraison'),
    path('sort/', views.sort, name='sort'),
    path('edit/<int:pk>/', views.edit_item, name='edit_item'),
]

urlpatterns += htmx_urlpatterns