# Generated by Django 5.0.3 on 2024-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='route',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
