# Generated by Django 5.0.3 on 2024-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_name_livraison_client_livraison_heure_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
