# Generated by Django 5.0.3 on 2024-03-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_livraison_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='livreur',
        ),
    ]
