# Generated by Django 5.0.3 on 2024-03-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_livreur_remove_livraison_name_livraison_livreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.livreur'),
        ),
    ]
