# Generated by Django 5.0.3 on 2024-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_client_alter_livraison_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='details',
            new_name='commentaire',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse_dock',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='adresse_lieux',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livraison',
            name='details_commande',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
