# Generated by Django 5.0.3 on 2024-03-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_livreur_livraisons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='livraisons',
        ),
    ]
