# Generated by Django 5.0.3 on 2024-03-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_livreur_livraisons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='livreur',
        ),
        migrations.AddField(
            model_name='livreur',
            name='livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.livraison'),
        ),
    ]
