# Generated by Django 5.0.3 on 2024-03-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_livreur_tacheafaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='tacheafaire',
        ),
    ]
