# Generated by Django 5.0.3 on 2024-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_livraison_heure_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='heure_depart',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='heure_livraison',
            field=models.CharField(max_length=100),
        ),
    ]
