# Generated by Django 5.0.3 on 2024-03-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_livraison_details_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='details_commande',
            field=models.FileField(upload_to='commandesdetail/'),
        ),
    ]
