# Generated by Django 5.0.3 on 2024-03-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_livreur_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='livraison',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='tacheafaire',
        ),
        migrations.CreateModel(
            name='Recuperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('heure_depart', models.CharField(max_length=100)),
                ('heure_livraison', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('commentaire', models.CharField(max_length=100)),
                ('details_commande', models.FileField(upload_to='commandesdetail/')),
                ('status', models.CharField(max_length=100)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.client')),
            ],
        ),
        migrations.AddField(
            model_name='livreur',
            name='recuperation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.recuperation'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.livraison'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='tacheafaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.tacheafaire'),
        ),
    ]
