# Generated by Django 5.0.3 on 2024-03-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_livraison_aidelivreur_recuperation_aidelivreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='journee',
        ),
        migrations.RemoveField(
            model_name='recuperation',
            name='journee',
        ),
        migrations.AddField(
            model_name='journee',
            name='livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.livraison'),
        ),
        migrations.AddField(
            model_name='journee',
            name='recuperation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.recuperation'),
        ),
    ]
