# Generated by Django 5.0.3 on 2024-03-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_remove_livraison_journee_remove_recuperation_journee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journee',
            name='livraison',
        ),
        migrations.RemoveField(
            model_name='journee',
            name='recuperation',
        ),
        migrations.AddField(
            model_name='livraison',
            name='journee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.journee'),
        ),
        migrations.AddField(
            model_name='recuperation',
            name='journee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.journee'),
        ),
    ]
