# Generated by Django 5.0.3 on 2024-03-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_remove_journee_livraison_remove_journee_recuperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='checklist',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
