# Generated by Django 5.0.3 on 2024-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_livraison_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='details_commande',
            field=models.FileField(upload_to='media/commandesdetail/'),
        ),
    ]
