# Generated by Django 5.0.3 on 2024-04-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_alter_livraison_aidelivreur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='journee',
            new_name='journe',
        ),
    ]
