# Generated by Django 5.0.3 on 2024-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_remove_client_adress_remove_client_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
