# Generated by Django 5.0.3 on 2024-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0054_livraison_contact_site_livraison_convives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='convives',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='infodetail',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
    ]
