# Generated by Django 5.0.3 on 2024-04-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0056_alter_livraison_num_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='aidelivreur',
            field=models.CharField(blank=True, choices=[('Osnel', 'Osnel'), ('Aucun', 'Aucun')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='checklist',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='recuperation',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='retourtraiteur',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
    ]
