# Generated by Django 5.0.3 on 2024-05-04 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0062_rename_important_livraison_commentairedispatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='journee',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.journee'),
        ),
    ]
