# Generated by Django 5.0.3 on 2024-05-04 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0063_alter_livraison_journee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='route',
        ),
        migrations.AddField(
            model_name='route',
            name='livraisons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.livraison'),
        ),
    ]
