# Generated by Django 5.0.3 on 2024-05-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0065_remove_route_livraisons_livraison_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='listings.route'),
        ),
    ]
