# Generated by Django 5.0.3 on 2024-05-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0066_alter_livraison_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='aidelivreur',
            field=models.CharField(blank=True, choices=[('Osnel', 'Osnel'), ('Jef', 'Jef'), ('Loic', 'Loic'), ('Maxime', 'Maxime'), ('Mohammad', 'Mohammad'), ('Samuel', 'Samuel'), ('Anthonny', 'Anthonny'), ('Bruno', 'Bruno'), ('Dany', 'Dany'), ('Rooseph', 'Rooseph'), ('Aucun', 'Aucun')], max_length=100, null=True),
        ),
    ]
