# Generated by Django 5.0.3 on 2024-05-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0070_alter_livraison_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
