# Generated by Django 5.0.3 on 2024-05-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0086_alter_livraison_aidelivreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
    ]
