# Generated by Django 5.0.3 on 2024-06-03 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0089_alter_livraison_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='photo',
        ),
        migrations.CreateModel(
            name='LivraisonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.livraison')),
            ],
        ),
    ]
