# Generated by Django 5.0.3 on 2024-06-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0091_livraison_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='listings/media/commandesdetail/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.livraison')),
            ],
        ),
        migrations.DeleteModel(
            name='LivraisonPhoto',
        ),
    ]
