# Generated by Django 5.0.3 on 2024-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0092_productphoto_delete_livraisonphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
