# Generated by Django 5.0.3 on 2024-07-04 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0096_remove_checklist_item_checklist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
