# Generated by Django 5.0.3 on 2024-07-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0098_alter_checklist_conseillere_alter_checklist_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminv',
            name='quantity',
        ),
        migrations.AddField(
            model_name='checklist',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='item',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.iteminv')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.iteminv'),
        ),
    ]
