# Generated by Django 5.0.3 on 2024-07-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0099_remove_iteminv_quantity_checklist_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='quantity',
        ),
    ]
