# Generated by Django 5.0.3 on 2024-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0102_product_rename_nom_checklist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
