# Generated by Django 5.0.3 on 2024-07-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0104_alter_checklistitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='md',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
