# Generated by Django 5.0.3 on 2024-07-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0106_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Equipement de base', 'Equipement de base'), ('Jetable', 'Jetable'), ('Accessoire de décor', 'Accessoire de décor'), ('Equipement de bar', 'Equipement de bar'), ('Equipement pour service café', 'Equipement pour service café'), ('Table et linge de table', 'Table et linge de table'), ('Verrerie', 'Verrerie'), ('Porcelaine et coutellerie', 'Porcelaine et coutellerie'), ('Equipement pour montage canapés', 'Equipement pour montage canapés'), ('Equipement de cuisson', 'Equipement de cuisson'), ('Ustensiles de service', 'Ustensiles de service'), ('Items divers', 'Items divers')], max_length=100),
        ),
    ]
