# Generated by Django 5.0.3 on 2024-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0108_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_cours', max_length=10),
        ),
    ]
