# Generated by Django 5.0.3 on 2024-07-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0113_alter_checklistitem_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('checklist', 'product')},
        ),
    ]
