# Generated by Django 5.0.3 on 2024-08-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0114_alter_checklistitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='status',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
