# Generated by Django 5.0.3 on 2024-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0115_remove_checklistitem_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_cours', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('checklist', 'product', 'status')},
        ),
    ]
