# Generated by Django 5.0.3 on 2024-08-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0118_checklist_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='total_quantity',
        ),
    ]
