# Generated by Django 5.0.3 on 2024-08-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0119_remove_checklist_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='journee',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.journee'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='aidelivreur',
            field=models.CharField(blank=True, choices=[('Osnel', 'Osnel'), ('Jef', 'Jef'), ('Loic', 'Loic'), ('Maxime', 'Maxime'), ('Mohammad', 'Mohammad'), ('Samuel', 'Samuel'), ('Anthonny', 'Anthonny'), ('Mohamed', 'Mohamed'), ('Dany', 'Dany'), ('Rooseph', 'Rooseph'), ('Aucun', 'Aucun')], default=' ', max_length=100, null=True),
        ),
    ]
