# Generated by Django 5.0.3 on 2024-08-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0120_route_journee_alter_livraison_aidelivreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='journee',
        ),
    ]
