# Generated by Django 5.0.3 on 2024-08-28 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0121_remove_route_journee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='journee',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.journee'),
        ),
    ]
