# Generated by Django 5.0.3 on 2024-09-15 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0126_tacheafaire_commentaire_tacheafaire_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(default='', upload_to='listings/media/products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='listings.product'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/media/commandesdetail')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_photos', to='listings.livraison')),
            ],
        ),
        migrations.DeleteModel(
            name='LivraisonPhoto',
        ),
    ]
