# Generated by Django 5.0.3 on 2024-09-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0127_remove_productphoto_photo_productphoto_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phototaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/media/commandesdetail')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tache_photos', to='listings.tacheafaire')),
            ],
        ),
    ]
