# Generated by Django 5.0.3 on 2024-09-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0131_alter_recupfrigoitem_recupfrigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recupfrigo',
            name='livraison',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='livraison_recupfrigo', to='listings.livraison'),
        ),
    ]
