# Generated by Django 5.0.3 on 2024-09-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0133_alter_recuplivreuritem_recuplivreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
    ]
