# Generated by Django 5.0.3 on 2024-10-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0140_itemcuisine_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcuisine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
    ]
