# Generated by Django 5.0.3 on 2024-10-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0143_remove_itemcuisine_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livreur',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
