# Generated by Django 5.0.3 on 2024-10-28 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0146_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.livreur'),
        ),
    ]
