# Generated by Django 5.0.3 on 2024-10-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0149_loadingdock'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingdock',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
