# Generated by Django 5.0.3 on 2024-10-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0151_md_alter_checklist_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='md',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='md',
            name='user',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='md',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
