# Generated by Django 5.0.3 on 2024-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0154_checklist_rapportmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='commentairevente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='photosrapport',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='photosrecup',
            field=models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail'),
        ),
    ]
