# Generated by Django 5.0.3 on 2024-10-31 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0155_checklist_commentairevente_checklist_photosrapport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='photosrapport',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='photosrecup',
        ),
        migrations.CreateModel(
            name='ChecklistMDPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/media/commandesdetail')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistRecupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/media/commandesdetail')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.checklist')),
            ],
        ),
    ]
