# Generated by Django 5.0.3 on 2024-11-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0165_alter_shift_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
    ]
