# Generated by Django 5.0.3 on 2024-11-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0166_remove_shift_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
