# Generated by Django 5.0.3 on 2024-11-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0170_quantityproductchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='notechecklist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
