# Generated by Django 5.0.3 on 2024-11-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0173_alter_checklist_conseillere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='conseillere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='listings.conseiller'),
        ),
    ]
