# Generated by Django 5.0.3 on 2024-11-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0175_alter_checklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_cours', max_length=20),
        ),
    ]
