# Generated by Django 5.0.3 on 2024-12-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0178_checklistitem_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='commentairedispatch',
            field=models.CharField(blank=True, default=' ', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='infodetail',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='loadingdock',
            name='link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
