# Generated by Django 5.0.3 on 2024-12-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0179_alter_livraison_commentairedispatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ÉQUIPEMENT DE BASE', 'ÉQUIPEMENT DE BASE'), ('JETABLE', 'JETABLE'), ('ACCESSOIRES DE DÉCOR', 'ACCESSOIRES DE DÉCOR'), ('ÉQUIPEMENT DE BAR', 'ÉQUIPEMENT DE BAR'), ('ÉQUIPEMENT POUR SERVICE CAFÉ', 'ÉQUIPEMENT POUR SERVICE CAFÉ'), ('TABLE ET LINGE DE TABLE', 'TABLE ET LINGE DE TABLE'), ('VERRERIE', 'VERRERIE'), ('PORCELAINE ET COUTELLERIE', 'PORCELAINE ET COUTELLERIE'), ('ÉQUIPEMENT POUR MONTAGE CANAPÉS', 'ÉQUIPEMENT POUR MONTAGE CANAPÉS'), ('ÉQUIPEMENT DE CUISSON', 'ÉQUIPEMENT DE CUISSON'), ('USTENSILES DE SERVICE', 'USTENSILES DE SERVICE'), ('BREUVAGE', 'BREUVAGE'), ('ALCOOL FORT', 'ALCOOL FORT'), ('BIERES', 'BIERES'), ('VINS', 'VINS'), ('SANS ALCOOL', 'SANS ALCOOL')], max_length=100),
        ),
    ]
