# Generated by Django 5.1.4 on 2025-01-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0187_checklistitem_previous_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='previous_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
