# Generated by Django 5.1.4 on 2025-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0188_checklistitem_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='is_stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
