# Generated by Django 5.1.4 on 2025-02-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0189_checklistitem_is_stock_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='period',
            field=models.CharField(blank=True, choices=[('matin', 'Matin'), ('midi', 'Midi'), ('apres_midi', 'Après-midi')], max_length=20, null=True),
        ),
    ]
