# Generated by Django 5.1.4 on 2025-02-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0190_livraison_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='commentaire',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
