# Generated by Django 5.1.4 on 2025-02-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0191_route_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='commentaire',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
