# Generated by Django 5.1.4 on 2025-02-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0194_checklist_created_checklist_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('modifié', 'Modifié'), ('verifié', 'Verifié')], default='en_cours', max_length=20),
        ),
    ]
