# Generated by Django 5.1.4 on 2025-02-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0195_alter_checklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='statusro',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('modifié', 'Modifié'), ('verifié', 'Verifié')], default='nouveau', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_cours', max_length=20),
        ),
    ]
