# Generated by Django 5.1.4 on 2025-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0196_checklist_statusro_alter_checklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='previous_statusro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
