# Generated by Django 5.1.4 on 2025-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0204_remove_route_livreur_route_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='livreur',
        ),
        migrations.AddField(
            model_name='route',
            name='livreur',
            field=models.ManyToManyField(blank=True, related_name='routes', to='listings.livreur'),
        ),
    ]
