# Generated by Django 5.1.4 on 2025-03-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0216_remove_vehicle_user_remove_route_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='listings/media/commandesdetail')),
                ('routes', models.ManyToManyField(blank=True, related_name='vehicles_list', to='listings.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='routes_vehicules', to='listings.vehicle'),
        ),
    ]
