# Generated by Django 5.1.4 on 2025-03-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0217_vehicle_route_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(choices=[('KingKong', 'KingKong'), ('Yeti', 'Yeti')], max_length=100),
        ),
    ]
