# Generated by Django 5.1.4 on 2025-04-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0220_alter_livraison_options_alter_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
