# Generated by Django 5.1.4 on 2025-04-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0221_vehicle_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/media/commandesdetail')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_photos', to='listings.vehicle')),
            ],
        ),
    ]
