# Generated by Django 5.1.4 on 2025-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0226_checklist_commodite_checklist_debut_cocktail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrecupphoto',
            name='commentaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
