# Generated by Django 5.1.4 on 2025-04-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0228_rename_commentaire_checklistrecupphoto_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrecupphoto',
            name='commentaire',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
