# Generated by Django 5.1.4 on 2025-04-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0229_checklistrecupphoto_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistrecupphoto',
            name='commentaire',
        ),
    ]
