# Generated by Django 5.1.4 on 2025-04-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0230_remove_checklistrecupphoto_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmdphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
