# Generated by Django 5.1.4 on 2025-04-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0231_checklistmdphoto_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmdphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings/media/videos'),
        ),
        migrations.AddField(
            model_name='checklistrecupphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings/media/videos'),
        ),
    ]
