# Generated by Django 5.1.4 on 2025-05-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0237_alter_submission_submission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('envoyé', 'Envoyé')], default='en_cours', max_length=20),
        ),
    ]
