# Generated by Django 5.1.4 on 2025-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0239_alter_submission_submission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('Soumission événement', 'Soumission_événement'), ('Commande événement', 'Commande_événement'), ('Soumission BAL/Buffet', 'Soumission_BAL_Buffet'), ('Commande BAL/Buffet', 'Commande_BAL_Buffet')], max_length=24),
        ),
    ]
