# Generated by Django 5.1.4 on 2025-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0240_alter_submission_submission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='refusal_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
