# Generated by Django 5.1.4 on 2025-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0242_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('assiette', 'Assiette'), ('buffet_porcelaine', 'Buffet porcelaine'), ('buffet_jetable', 'Buffet jetable'), ('coffret', 'Coffret'), ('menu', 'Menu')], max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='delivery_mode',
        ),
        migrations.AddField(
            model_name='submission',
            name='delivery_modes',
            field=models.ManyToManyField(blank=True, to='listings.deliverymode'),
        ),
    ]
