# Generated by Django 5.1.4 on 2025-05-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0243_deliverymode_remove_submission_delivery_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='menus',
            field=models.ManyToManyField(blank=True, to='listings.menu'),
        ),
    ]
