# Generated by Django 5.1.4 on 2025-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0245_rename_menus_submission_sub_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
