# Generated by Django 5.1.4 on 2025-05-08 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0247_remove_submission_delivery_modes_menu_allergie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, null=True)),
                ('delivery_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.deliverymode')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.menu')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_submissions', to='listings.submission')),
            ],
        ),
    ]
