# Generated by Django 5.1.4 on 2025-05-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0248_menusubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='commentaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
