# Generated by Django 5.1.4 on 2025-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0251_loadingdock_adresse_compagny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='loading_dock',
        ),
        migrations.AddField(
            model_name='livraison',
            name='loading_docks',
            field=models.ManyToManyField(blank=True, related_name='livraisons', to='listings.loadingdock'),
        ),
    ]
