# Generated by Django 5.1.4 on 2025-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0252_remove_livraison_loading_dock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='loading_docks',
            field=models.ManyToManyField(blank=True, related_name='livraisons_dock', to='listings.loadingdock'),
        ),
    ]
