# Generated by Django 5.1.4 on 2025-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0254_plat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='nom',
            field=models.CharField(max_length=130),
        ),
    ]
