# Generated by Django 5.1.4 on 2025-05-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0255_alter_plat_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='nom_english',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
