# Generated by Django 5.1.4 on 2025-06-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0259_alter_plat_nom_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='nom',
            field=models.CharField(max_length=160),
        ),
    ]
