# Generated by Django 5.1.4 on 2025-06-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0260_alter_plat_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusubmission',
            name='service_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
