# Generated by Django 5.1.4 on 2025-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0261_menusubmission_service_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ascenseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='avec_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='carte_dock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='dock_livraison',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='escalier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='etage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
