# Generated by Django 5.1.4 on 2025-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0266_submission_event_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='commentaire_menu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
