# Generated by Django 5.1.4 on 2025-06-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0269_paymentmode_alter_client_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cc', 'Carte de Crédit'), ('cheque', 'Chèque'), ('interac', 'Interac')], max_length=20, null=True),
        ),
    ]
