# Generated by Django 5.1.4 on 2025-06-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0275_alter_submission_type_prise_de_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='type_prise_de_commande',
            field=models.CharField(blank=True, choices=[('Téléphone', 'Téléphone'), ('En ligne', 'En ligne'), ('Courriel', 'Courriel')], max_length=10, null=True),
        ),
    ]
