# Generated by Django 5.1.4 on 2025-06-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0276_alter_submission_type_prise_de_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='event_location',
        ),
    ]
