# Generated by Django 5.1.4 on 2025-06-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0281_client_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
