# Generated by Django 5.1.4 on 2025-06-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0282_alter_submission_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
