# Generated by Django 5.1.4 on 2025-07-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0283_alter_livreur_latitude_alter_livreur_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journee',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
