# Generated by Django 5.1.4 on 2025-07-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0285_submission_billing_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='location_materiel',
            field=models.BooleanField(default=False),
        ),
    ]
