# Generated by Django 5.1.4 on 2025-07-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0286_submission_language_submission_location_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
