# Generated by Django 5.1.4 on 2025-07-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0287_alter_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='avec_service_md',
            field=models.BooleanField(default=False),
        ),
    ]
