# Generated by Django 5.1.4 on 2025-07-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0288_submission_avec_service_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubmission',
            name='delivery_mode',
            field=models.ForeignKey(blank=True, default='Valeur non définie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.deliverymode'),
        ),
    ]
