# Generated by Django 5.1.4 on 2025-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0290_alter_category_name_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
