# Generated by Django 5.1.4 on 2025-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0291_submission_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='commentaire',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
