# Generated by Django 5.1.6 on 2025-09-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0292_alter_submission_commentaire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('checklist', 'product')},
        ),
    ]
