# Generated by Django 4.2.23 on 2025-09-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0298_departement_fournisseur_recette_sousrecette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
