# Generated by Django 4.2.23 on 2025-09-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0299_lignecommande_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AddField(
            model_name='commande',
            name='notes_validation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='validation_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
