# Generated by Django 4.2.23 on 2025-09-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0300_alter_commande_options_commande_notes_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation de cette ligne', null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='qualite_validation',
            field=models.CharField(blank=True, choices=[('OK', 'Qualité OK'), ('PROBLEME', 'Problème qualité'), ('NON_VERIFIE', 'Non vérifié')], default='NON_VERIFIE', help_text='Statut de la qualité lors de la réception', max_length=20),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='quantite_recue',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantité réellement reçue lors de la validation', max_digits=10, null=True),
        ),
    ]
