# Generated by Django 4.2.23 on 2025-09-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0302_character_difficultylevel_score1'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du personnage (format recommandé: 200x200px)', null=True, upload_to='characters/', verbose_name='Image du personnage'),
        ),
    ]
