# Generated by Django 4.2.23 on 2025-10-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0304_ballskin_playerskin_powerup_alter_score_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultylevel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Difficulté disponible pour les joueurs', verbose_name='Actif'),
        ),
    ]
