# Generated by Django 4.2.23 on 2025-10-01 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0305_difficultylevel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerskin',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='listings.character', verbose_name='Personnage associé'),
        ),
    ]
