# Generated by Django 4.2.23 on 2025-10-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0306_playerskin_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='notes',
            field=models.TextField(blank=True, help_text='Informations supplémentaires'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='procedure_commande',
            field=models.TextField(blank=True, help_text='Procédure et horaires de commande'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='type_produits',
            field=models.TextField(blank=True, help_text='Types de produits fournis'),
        ),
    ]
