# Generated by Django 4.2.23 on 2025-10-03 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0307_fournisseur_notes_fournisseur_procedure_commande_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cataloguefournisseur',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cataloguefournisseur',
            name='devise',
            field=models.CharField(choices=[('CAD', '$CAD'), ('EUR', '€EUR'), ('USD', '$USD')], default='CAD', max_length=3),
        ),
        migrations.AddField(
            model_name='cataloguefournisseur',
            name='quantite_par_unite',
            field=models.DecimalField(decimal_places=3, default=1, help_text="Quantité par unité d'achat (ex: 5kg par sac)", max_digits=10),
        ),
        migrations.AddField(
            model_name='cataloguefournisseur',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.unitemesure'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unite_achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredients_achat', to='listings.unitemesure'),
        ),
        migrations.AddField(
            model_name='unitemesure',
            name='facteur_conversion',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='unitemesure',
            name='type_usage',
            field=models.CharField(choices=[('ACHAT', 'Achat (Fournisseur)'), ('RECETTE', 'Recette (Production)'), ('BOTH', 'Les deux')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='unitemesure',
            name='unite_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.unitemesure'),
        ),
        migrations.AlterField(
            model_name='cataloguefournisseur',
            name='prix',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unite_mesure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients_recette', to='listings.unitemesure'),
        ),
    ]
